flexbox: initial attempt to add support for RTL direction
Kozea/WeasyPrint pull request #1225
Opened 2020-10-03 17:47 UTC by malnajdi

I have added:
1. 2 test cases for flexbox with direction RTL. 
2. modified the code which handles flexbox to add RTL aware code.

related #601

2020-10-07 20:39 UTC, liZe requested changes

2020-10-07 20:39 UTC, liZe commented on weasyprint/layout/flex.py
> +        if box.style['direction'] == 'rtl':
The logical part here is good. A nice improvement would be to multiply `free_space` by `-1` here if direction is `rtl`, it would help keeping only one block below instead of duplicating it.

2020-10-07 20:39 UTC, liZe commented on weasyprint/layout/flex.py
> +        if box.style['direction'] == 'rtl':
And I’m not sure that it works when `flex-direction` is `column`, because we don’t have to revert the (vertical) axis in this case.

2020-10-07 20:39 UTC, liZe commented on weasyprint/tests/test_layout/test_flex.py
> +@assert_no_logs
👍🏼

2020-10-07 20:39 UTC, liZe commented on weasyprint/tests/test_layout/test_flex.py
>  @assert_no_logs
Adding tests here with `rtl` + `column` is a good idea.

2020-10-10 18:47 UTC, malnajdi commented on weasyprint/layout/flex.py
> +        if box.style['direction'] == 'rtl':
I have added extra if statement to ensure the logic is applied only if  `flex-direction` starts with row-

2020-10-10 18:48 UTC, malnajdi commented on weasyprint/layout/flex.py
> +        if box.style['direction'] == 'rtl':
I have tried to add what you required but it breaks the flex items

2020-10-10 19:05 UTC, malnajdi commented on weasyprint/tests/test_layout/test_flex.py
>  @assert_no_logs
done

2020-10-10 19:06 UTC, malnajdi commented on weasyprint/tests/test_layout/test_flex.py
> +    assert (
@liZe please verify if this test is correct.

2020-10-10 19:06 UTC, malnajdi commented on weasyprint/tests/test_layout/test_flex.py
> +    assert div_3.position_x == article.position_x
@liZe please verify if this test is correct.

2020-10-21 18:46 UTC, liZe commented
Thanks a lot! No problem, I’ll simplify the "if rtl" part of your PR in a future commit.

2020-10-21 18:46 UTC, merged