Reuse decompressed woff files based on hash
Kozea/WeasyPrint pull request #1505
Opened 2021-11-23 16:59 UTC by ColinKinloch

When adding a woff font to a `FontConfiguration` only decode it if it is new.

Brings my build times down from 140s to 12s.

Sorry about #1495 and #1500. I didn't realise that the fonts filename was being used by font config as an unique id for its properties.

2021-11-28 19:02 UTC, liZe requested changes
Thanks a lot for the PR!

Could you please fix the couple of problems listed in the comments? Apart from that, the PR looks good to me, we can merge it for version 54.

2021-11-28 19:02 UTC, liZe commented on weasyprint/text/fonts.py
> +                            if font[3:4] == b'F':
We should just use `font[3]`, I don’t know why I’ve used `3:4` instead…

2021-11-28 19:02 UTC, liZe commented on weasyprint/text/fonts.py
> +                            fd = open('rb', decoded_woff_path)
That’s `open(decoded_woff_path, 'rb')`. So, I suspect that this code is actually untested 😁.

A better solution is to use `Path(decoded_woff_path).read_bytes()` instead: it’s easier to read, and there’s no need to close the file.

2021-11-28 20:15 UTC, ColinKinloch commented on weasyprint/text/fonts.py
> +                            if font[3:4] == b'F':
It seems font[3] returns a number, font[3:4] returns a bytes

2021-11-28 20:31 UTC, ColinKinloch commented on weasyprint/text/fonts.py
> +                            fd = open('rb', decoded_woff_path)
:facepalm: I've added a second woff font-face to the test.

2021-11-28 20:43 UTC, liZe approved these changes

2021-11-29 11:24 UTC, liZe commented
Thank you!

2021-11-29 11:24 UTC, merged